import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';
import { catchError } from 'rxjs/operators';


import { HttpErrorHandlerService, HandleError } from '../http-error-handler.service';

const httpOptions = {
  headers: new HttpHeaders({
    'Content-Type':  'application/json',
    'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im1lIiwiZXhwIjoxNTY5MzE5NTg2LCJ1c2VyIjp7InVzZXJuYW1lIjoibWUiLCJyb2xlcyI6WyJhZG1pbiJdLCJhcGlfdG9rZW4iOiJmNmIyNGY1MDZlYzI4NTliZjRjZGZjNTRkOTFkMmMzMzVlMzYwZTA2In0sInNjb3BlcyI6WyJidWxrRGF0YTpnZXQiLCJleGFtcGxlczp1cGRhdGUiLCJjbGllbnRzOmdldCIsImVudmlyb25tZW50czp1cGRhdGUiLCJzdG9yaWVzOmRlbGV0ZSIsImNsaWVudEV2ZW50czpjcmVhdGUiLCJhbmFseXRpY3M6Z2V0IiwiY2xpZW50RXZhbHVhdGlvbjpnZXQiLCJkb21haW5XYXJuaW5nczpnZXQiLCJtb2RlbHMuc2V0dGluZ3M6dXBkYXRlIiwicm9sZXMudXNlcnM6bGlzdCIsImJ1bGtTdG9yaWVzOnVwZGF0ZSIsIm1vZGVscy50YWdzOnVwZGF0ZSIsIm1ldGFkYXRhOmNyZWF0ZSIsImFjdGlvblByZWRpY3Rpb246Z2V0IiwiZXhhbXBsZXM6Z2V0IiwidXNlcnM6Y3JlYXRlIiwiYWxsRXZhbHVhdGlvbnM6Y3JlYXRlIiwicm9sZXM6bGlzdCIsImV4YW1wbGVzOmxpc3QiLCJpbnRlbnRzOmRlbGV0ZSIsImxvZ3M6bGlzdCIsImxvZ3M6Y3JlYXRlIiwiZXhhbXBsZXM6ZGVsZXRlIiwidXNlcnMucm9sZXM6bGlzdCIsIm1lc3NhZ2VGbGFnczpkZWxldGUiLCJtb2RlbHMuZXZhbHVhdGlvbnM6bGlzdCIsImxvZ3M6Z2V0IiwibW9kZWxzOmxpc3QiLCJkb21haW46dXBkYXRlIiwiY2hhdFRva2VuOmdldCIsImNsaWVudE1lc3NhZ2VzOmxpc3QiLCJ1c2VyczpkZWxldGUiLCJtb2RlbHMuc2V0dGluZ3M6Z2V0IiwibW9kZWxzOmRlbGV0ZSIsImRvbWFpbkFjdGlvbnM6Z2V0IiwidXNlckdvYWxzOmNyZWF0ZSIsInVzZXIucGFzc3dvcmQ6dXBkYXRlIiwiaW50ZW50czp1cGRhdGUiLCJ1c2VyOmdldCIsInJvbGVzLnVzZXJzOnVwZGF0ZSIsInVzZXJzOmxpc3QiLCJyb2xlczp1cGRhdGUiLCJhY3Rpb25QcmVkaWN0aW9uOmNyZWF0ZSIsImZlYXR1cmVzOmNyZWF0ZSIsInByb2plY3RzOmNyZWF0ZSIsIm1vZGVscy50YWdzOmRlbGV0ZSIsInJvbGVzOmNyZWF0ZSIsImNvbnZlcnNhdGlvbkFjdGlvbnM6bGlzdCIsInN0YXRpc3RpY3M6Z2V0IiwibWV0YWRhdGE6bGlzdCIsIm1ldGFkYXRhOmdldCIsIm1lc3NhZ2VzOmNyZWF0ZSIsImJ1bGtTdG9yaWVzOmdldCIsImNoYXRUb2tlbjp1cGRhdGUiLCJyZXNwb25zZVRlbXBsYXRlczpjcmVhdGUiLCJsb2dzOmxpc3QiLCJyZXNwb25zZVRlbXBsYXRlczpsaXN0IiwiZXhhbXBsZXM6Y3JlYXRlIiwibWVzc2FnZUludGVudHM6dXBkYXRlIiwiY29udmVyc2F0aW9uRW50aXRpZXM6bGlzdCIsInJvbGVzOmRlbGV0ZSIsIm5sZ1Jlc3BvbnNlOmNyZWF0ZSIsImludGVudHM6Y3JlYXRlIiwibWVzc2FnZUludGVudHM6ZGVsZXRlIiwiY2xpZW50RXZhbHVhdGlvbjpkZWxldGUiLCJlbnZpcm9ubWVudHM6bGlzdCIsInVzZXI6dXBkYXRlIiwiY29udmVyc2F0aW9uUG9saWNpZXM6bGlzdCIsIm1vZGVscy5tb2RlbEJ5VGFnOmdldCIsImludGVudHM6bGlzdCIsImRvbWFpbjpnZXQiLCJzdG9yaWVzOmdldCIsIm1vZGVscy5ldmFsdWF0aW9uczp1cGRhdGUiLCJidWxrRGF0YTp1cGRhdGUiLCJyb2xlczpnZXQiLCJtb2RlbHM6Z2V0Iiwic3Rvcmllczp1cGRhdGUiLCJtb2RlbHMuZXZhbHVhdGlvbnM6Z2V0IiwiYnVsa1Jlc3BvbnNlVGVtcGxhdGVzOnVwZGF0ZSIsIm1lc3NhZ2VGbGFnczp1cGRhdGUiLCJzdG9yaWVzOmxpc3QiLCJyZXNwb25zZVRlbXBsYXRlczpkZWxldGUiLCJ1c2VyR29hbHM6ZGVsZXRlIiwiY2xpZW50RXZhbHVhdGlvbjp1cGRhdGUiLCJjb252ZXJzYXRpb25JbnRlbnRzOmxpc3QiLCJjbGllbnRFdmVudHM6dXBkYXRlIiwicmVzcG9uc2VUZW1wbGF0ZXM6dXBkYXRlIiwidXNlcnMucm9sZXM6dXBkYXRlIiwibG9nczpkZWxldGUiLCJtb2RlbHMuZXZhbHVhdGlvbnM6ZGVsZXRlIiwibW9kZWxzLmpvYnM6Y3JlYXRlIiwid2FybmluZ3M6Z2V0Iiwic3RvcmllczpjcmVhdGUiLCJ1c2Vycy5yb2xlczpkZWxldGUiLCJhbGxFdmFsdWF0aW9uczpsaXN0IiwiZW50aXRpZXM6bGlzdCIsIm1vZGVsczpjcmVhdGUiXX0.JzLhavpYCuXmIsWM534Qrqzrr_M_87WwzkHsbG5ZelA'
  })
};
@Injectable({
  providedIn: 'root'
})
export class SettingsService {

  configUrl = 'http://3.14.100.246:5002/api/projects/default/settings';  // URL to web api

  private handleError: HandleError;

  constructor(private http: HttpClient,httpErrorHandler: HttpErrorHandlerService) { 
    this.handleError = httpErrorHandler.createHandleError('SettingsService');
  }

   /** GET Config Data from the server */
   getConfigData (): Observable<any> {
    const url =`${this.configUrl}`; // GET api/projects/default/settings
    return this.http.get<any>(url,httpOptions)
      .pipe(
        catchError(this.handleError('getConfigData', []))
      );
  }
}
